
datadump.location:
    author: /Users/dawidkaszuba/Documents/nauka/betterreads/data/test-authors.txt
    works: /Users/dawidkaszuba/Documents/nauka/betterreads/data/test_works.txt

spring:
    cassandra:
      keyspace-name: main
      username: PuYPlyRZjvUMteAFMcuoXNHa
      password: rEHAGZBvWcRlZmST7vLAjWi5Yh8l,h7nlzhiGPPcGU5Eob1ZkpSH,F0QuPNy52RANnohR6WZ_3JA+h8KevAAxte_TZlZ00NJxN+LjceTWA+kkgNtSxB9bcI5QqelHM5c
      schema-action: create-if-not-exists
      #schema-action: recreate
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
    application:
        name: betterreads-data-loader


    main:
        allow-circular-references: true

datastax:
    astra:
        secure-connect-bundle: secure-connect.zip
astra.db:
    id: 7769a649-8b75-4262-9264-0a77a678a629-1
    region: europe-west1
    keyspace: main
    application.token: AstraCS:PuYPlyRZjvUMteAFMcuoXNHa:3521e04aaf410c5cb736c9408da012aea6fe3429d0692ff3aa5ee43d6dc3a4a1


